#!/bin/sh

rm -f /etc/rc.d/S??frp /etc/rc.d/K??frp

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frp[-1]
	delete ucitrack.@multi-frpc[-1]
	add ucitrack multi-frpc
	set ucitrack.@multi-frpc[-1].init=multi-frpc
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache/
exit 0
